### ISSUE TITLE
Batavia transformers don't move transformed classes to appropriate packages

### ISSUE THREAD

**Issue by ropalka** [wildfly-extras/batavia#22]
Both "no dependencies" transformer and "asm-based" transformer don't remap transformed classes to appropriate packages. This causes issues with JBoss modules framework where module metadata are generated according to detected packages in particular jar file.

**Comment by scottmarlow** [comment]
Can you please show an example of what you mean by appropriate packages.

**Comment by ropalka** [comment]
For example when we are transforming servlet-api.jar to jakarta-servlet-api.jar class files content is transformed but transformed classes remain in javax packages in output jar file.

**Comment by ropalka** [comment]
We can't close this issue yet. @scottmarlow is looking into minor issue with ASM based transformer.

**Comment by ropalka** [comment]
This is fixed now @jfdenise
