### ISSUE TITLE
Deal with jaxb context factory properties

### ISSUE THREAD

**Issue by bstansberry** [wildfly-extras/batavia#97]
JAXB includes a couple properties used to resolve interface implementations whose values have changed:

https://github.com/eclipse-ee4j/jaxb-api/blob/master/jaxb-api/src/main/java/jakarta/xml/bind/JAXBContext.java#L308
https://github.com/eclipse-ee4j/jaxb-api/blob/master/jaxb-api/src/main/java/jakarta/xml/bind/ContextFinder.java#L42

These are used to resolve by checking system properties, which is out of scope for batavia, but also using jaxb.properties files on the classpath, which are in scope.

**Comment by bstansberry** [comment]
BTW i'm not completely certain this isn't already handled, but some simple grepping of files I don't fully understand makes me believe it's not.

**Comment by scottmarlow** [comment]
Thanks @bstansberry , I'm not 100% sure either but think it should if not.

**Comment by bstansberry** [comment]
@scottmarlow @ropalka FYI the test updated in https://github.com/wildfly/wildfly/pull/13833 deal with these properties. Tweaking those might be a way of checking wF's behavior.  That PR basically configures things so both the javax and jakarta props are used. Disabling the jakarta prop and confirming it still works might verify this.

**Comment by scottmarlow** [comment]
I do see ee9 test failures after:

1.  updating org.jboss.as.test.integration.jaxb.unit.JAXBContextSystemPropCustomTestCase#getSystemProperties back to prior:
```
        protected SystemProperty[] getSystemProperties() {
            return new SystemProperty[] {
                new DefaultSystemProperty(JAXB_FACTORY_PROP_NAME, CUSTOM_JAXB_FACTORY_CLASS)
            };
        }
```
2. Starting EE9 standalone server 
3. cd wildfly/testsuite/integration/basic; mvn clean install -Dtest=org.jboss.as.test.integration.jaxb.unit.JAXBContextSystemPropCustomTestCase

**Comment by ropalka** [comment]
IMO you cannot remove JAKARTA_FACTORY_PROP_NAME from both 
JAXBContextSystemPropCustomTestCase  & JAXBContextSystemPropInternalTestCase @scottmarlow .
The server setup task adds these properties to DMR model of running server during the test and it
cannot be catched by transformer. On the other side what should work is 
JAXBContextUsingPropertiesTestCase test without JAKARTA_FACTORY_PROP_NAME .
I created proposal PR to address this: https://github.com/wildfly-extras/batavia/pull/98

**Comment by bstansberry** [comment]
+1 @ropalka re the tests that test what happens when the behavior is controlled by a system property. Batavia can't deal with that. JAXBContextUsingPropertiesTestCase uses a properties file inside the deployment; that's what deployment transformation should handle.
